version: 2
updates:
  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "/root-dir"
    schedule:
      interval: "daily"
    groups:
      dependencies:
        patterns:
          - "*"
